# Generated by Django 3.0.6 on 2020-05-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tipo_mascota',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
