# Generated by Django 3.0.6 on 2020-05-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_mascota_tipo_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='tipo_mascota',
        ),
    ]
