# Generated by Django 3.0.6 on 2020-05-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_remove_mascota_tipo_mascota'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tipo_mascota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
